### ISSUE TITLE
Only getting half of the stream

### ISSUE THREAD

**Issue by dejanpan** [orosandrei/Home-Monitoring-Raspberry-Pi-Node#1]
Hi there!
I forked your project as it looks like the best end-to-end solution for what I wonna do. Great work.

However I am hitting the wall right now. I got PI camera and I only wanted to get the video streaming done first, so I mostly commented out everything else in https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js.

The problem that I am having is that in resolution 640x480, 75% quality I only get parts of the image:
![screen shot 2016-07-13 at 22 09 02](https://cloud.githubusercontent.com/assets/17376/16818229/0647f620-4947-11e6-9ead-a8b5dc334046.png)

If I reduce the quality of the image I get more. It seems that the frames are coming from the stream in chunks here: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L221 but I do not really know how to compose them together. E.g. when do I know 1 frame has been fully transferred to that callback?

Any hints I would warmly appreciate.

**Comment by orosandrei** [comment]
1. I would also comment line https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L231 , you don't need it for basic streaming, it is used for alarm notifications
2. the video stream is generated by mjpg_streamer at http://localhost:3334/?action=stream .. so try to open that url after manually executing https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/start-webcam.sh and see if you get full frames
3. if you don't get full frames at point 2), change the mjpg_streamer arguments until you do - _see documentation here https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_raspicam/README.md_
4. if you do get full frames at point 2), the issue is in the JS code & you might need to emit new frames via websockets from the StreamingBuffer in a separate timer & not directly as they arrive (realtime, like it is now); then you'll have to uncomment point 1)

**Comment by dejanpan** [comment]
Thx @orosandrei. 
1. I actually had it commented out, I now pushed that too.
2. That works perfectly (also already tested yesterday):
![screen shot 2016-07-14 at 09 24 15](https://cloud.githubusercontent.com/assets/17376/16831428/39b393b2-49a5-11e6-94d1-73d303787d5f.png)
4. The point is that I actually debug save incoming frames here: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L240-L246 and see that they are already incomplete. Some are also "invalid" (e.g. image viewing program can't open them) which may be because of missing jpeg headers?
When you said JS code, you meant https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/static/js/script.js#L33?

thx

**Comment by orosandrei** [comment]
I think the issue is at https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L230 - try increasing the **newFrame.length > 1000** until you get full frames (it will exclude invalid frames smaller than the specified size); try with 2000 or more

If this doesn't work, you'll probably have to adjust the http stream headers at https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L20-L26 

As a last resort you could include the http://localhost:3334/?action=stream stream in an iframe in the static html and show the content directly, without processing it through the node app - this approach has 2 disadvantages from my point of view: 1) you need to open another port for access from outside your network 2) for alarms you'll need to capture the frames in the static js & send them back to the server via websockets, the opposite of how it is done today

**Comment by dejanpan** [comment]
My frame lengths:

> ewFrame.length  22
> newFrame.length  75
> newFrame.length  65536
> newFrame.length  65536
> newFrame.length  17589
> newFrame.length  75
> newFrame.length  65536
> newFrame.length  65536
> newFrame.length  17344
> newFrame.length  75
> newFrame.length  65536
> newFrame.length  65536
> newFrame.length  17715
> newFrame.length  75
> newFrame.length  65536
> newFrame.length  65536
> newFrame.length  17770
> newFrame.length  75
> newFrame.length  65536
> newFrame.length  65536
> newFrame.length  17674
> newFrame.length  75

What is interesting is a) there is a pattern in 1x75(header?), 2x65536, 1x17xxx and b) max http request buffer size seems to be 65K.  So the image almost definitely gets split into chunks. I will see if I can tinker with stream headers. iframe I also do not like.

**Comment by orosandrei** [comment]
I think you are right about the lengths; try building your frame from 3 consecutive chunks starting with the 75 one and only emit the final frame

**Comment by dejanpan** [comment]
Good news: I got the full frames. I tried 2 approaches.
1. check if it looks like a beginning of a  jpeg frame (See http://reddocode.blogspot.de/2015/05/stream-raspberry-pi-camera-module-from.html) and concat everything that follows until next beginning: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L235-L248
2. check for pattern where frame size goes 65K, 65K, .... <60K => concatenate, reset and loop again: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L249-L258

Both work however the problem with both approaches is that the stream is not smooth. E.g. frames get dropped in between. Also I noticed that the app doesn't really run at much faster than 5fps (640x480). I will keep looking into this next week.

~~Finally, it seems that there is a memory leak. If I comment out this line https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L268 the leak stops. So I then tried to check what is in https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/static/js/script.js#L33, commented out everything inside the callback but the leak was still there. 
Is it possible that io.connect leaks or would we need to free something explicitly?~~
Update:
I checked twice and now my memory is stable at 5fps. Can't say for sure what happened before.

**Comment by orosandrei** [comment]
I don't think the memory leak comes from the line https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/master/App-home-monitoring.js#L268 I checked my raspberry pi while streaming & memory + cpu are stable
![image](https://cloud.githubusercontent.com/assets/6123431/16845107/60284dee-49f0-11e6-99c2-ee52e8f2453e.png)

Regarding the JS in the client (browser), the memory usage did increase, but stabilized quite fast & periodically the memory drops (probably the GC kicking in)
![image](https://cloud.githubusercontent.com/assets/6123431/16845200/c2255596-49f0-11e6-87be-a80ac2cc448e.png)

_Update_: I took a look at the config of my generic webcam, it works with 640x480 at 25fps .. but I also have dropped frames occasionally. I'll try to do some optimizations of the video stream frames processing, based on your feedback.

**Comment by dejanpan** [comment]
I also updated my comment above. Now checked twice and memory stable at 5fps.

Further it seems that you need to parse a so called `boundary` when you parse mjpeg stream, see: http://en.code-bude.net/tag/how-does-mjpeg-work/. `It’s the separator pattern which tells the consumer (browser, media player, etc) of the stream where the image data blocks begin and end.`

This here seems to be a pretty good reference implementation https://github.com/legege/node-mjpeg-proxy/blob/master/mjpeg-proxy.js.

They also send it on the server side: https://github.com/jacksonliam/mjpg-streamer/blob/4d070dfb170652ef73018bf916ce073489f64fc3/mjpg-streamer-experimental/plugins/output_http/httpd.c#L531.

As said above I will have time to look into it from next Wed on (travelling home where internet is spotty).

**Comment by dejanpan** [comment]
@orosandrei 
I finally came up with this fix that works reliably for me @10fps, 640x480:
https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/commit/08873e3a4a110bb7183767243f2630ab9c6e41fb

It is basically more less a c/p of https://github.com/mmaelzer/mjpeg-consumer and it is based on the fact that you actively search for jpeg image begin and end in the stream of chunks: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/blob/08873e3a4a110bb7183767243f2630ab9c6e41fb/App-home-monitoring.js#L217-L222.

I will for now leave at this and focus on the rest. I'd say we can now close the issue unless you want to have what worked for me in your code as well.
